name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # SSH into the server and pull the latest code
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 78.47.239.56
          username: alex
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/alex/sources/alexcoll.in
            git pull origin main
            docker-compose down
            docker-compose up --build -d
